# Generated by Django 5.2.17 on 2026-08-17 21:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("styles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        default="Paula's African Hair Braiding", max_length=150
                    ),
                ),
                (
                    "address_line",
                    models.CharField(default="4203 Trio Avenue", max_length=255),
                ),
                ("city", models.CharField(default="Louisville", max_length=100)),
                ("state", models.CharField(default="KY", max_length=50)),
                ("zip_code", models.CharField(default="40219", max_length=20)),
                (
                    "email",
                    models.EmailField(
                        default="Pauletteagbeti@gmail.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "travel_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25.00"),
                        help_text="Flat fee added to bookings where Paula travels to the customer.",
                        max_digits=6,
                    ),
                ),
                (
                    "business_hours_note",
                    models.CharField(
                        blank=True,
                        default="Mon-Sat, 9:00 AM - 6:00 PM",
                        help_text="Shown to customers on the site (free text).",
                        max_length=255,
                    ),
                ),
                (
                    "days_closed",
                    models.CharField(
                        blank=True,
                        default="6",
                        help_text="Comma-separated weekday numbers she's closed (0=Mon ... 6=Sun). Default: Sunday.",
                        max_length=50,
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "business settings",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=30)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("salon", "At Paula's location"),
                            ("mobile", "Paula comes to me"),
                        ],
                        max_length=10,
                    ),
                ),
                ("customer_address", models.CharField(blank=True, max_length=255)),
                ("requested_date", models.DateField()),
                ("requested_time", models.TimeField()),
                (
                    "salon_price_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "travel_fee_snapshot",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hairstyle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="styles.hairstyleservice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
