# Generated by Django 5.2.17 on 2026-08-27 06:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("salon", "At Paulette's location"),
                    ("mobile", "Paulette comes to me"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="business_name",
            field=models.CharField(
                default="Paulette's African Hair Braiding", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="travel_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("25.00"),
                help_text="Flat fee added to bookings where Paulette travels to the customer.",
                max_digits=6,
            ),
        ),
    ]
