# Generated by Django 5.2.17 on 2026-08-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(upload_to="styles/gallery/"),
        ),
        migrations.AlterField(
            model_name="hairstyleservice",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="styles/covers/"),
        ),
    ]
