# Generated by Django 5.2.17 on 2026-08-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0002_alter_galleryimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hairstyleservice",
            name="price_display_override",
            field=models.CharField(
                blank=True,
                help_text='Optional. If set, this text replaces the price shown to customers everywhere on the site (e.g. "From $150+", "Book for a quote", "Price varies by length"). Leave blank to just show the price above.',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="hairstyleservice",
            name="salon_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price when the customer comes to Paula's location. Always used for the booking total, even if a display override below is set.",
                max_digits=7,
            ),
        ),
    ]
