# Generated by Django 5.2.17 on 2026-08-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("styles", "0003_hairstyleservice_price_display_override_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hairstyleservice",
            name="salon_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price when the customer comes to Paulette's location. Always used for the booking total, even if a display override below is set.",
                max_digits=7,
            ),
        ),
    ]
